spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/productsDB}
